// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbU3_Ob0iviDrJClPlXkaPv2NCgGHhW08',
    appId: '1:938446589442:web:a59fa227987e05486fa11b',
    messagingSenderId: '938446589442',
    projectId: 'signup-8a3bd',
    authDomain: 'signup-8a3bd.firebaseapp.com',
    storageBucket: 'signup-8a3bd.firebasestorage.app',
    measurementId: 'G-QN6N6H2WMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnigj-ARerwMZ-BYkQnLCtPiovCoyaO-0',
    appId: '1:938446589442:android:c5dc291266f544976fa11b',
    messagingSenderId: '938446589442',
    projectId: 'signup-8a3bd',
    storageBucket: 'signup-8a3bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfSjEIlAu2CA_2GpR90WNPCZQe6-LCFA',
    appId: '1:938446589442:ios:1e967304378f4fd86fa11b',
    messagingSenderId: '938446589442',
    projectId: 'signup-8a3bd',
    storageBucket: 'signup-8a3bd.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
